Repository 2Jo-Logistics-Management/smart-logistics-back, pull requests merged in 2023-09, with the labels that each got.

#59 Member/check
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/entity/MainPage.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/mainPage/api/MainPageController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/mainPage/application/MainPageService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/mainPage/dao/MainPageDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/mainPage/dao/mapper/MainPageMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/mainPage/dto/MainPageDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/api/MemberController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/application/MemberService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/dao/MemberDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/dao/mapper/MemberMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/config/WebConfiguration.java
  backend/smart-logistics/src/main/resources/mapper/mainPage/MainPageMapper.xml
  backend/smart-logistics/src/main/resources/mapper/member/MemberMapper.xml
Labels: feat

#60 Member/check
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/api/AccountController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/application/AccountService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dao/AccountDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dao/mapper/AccountMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dto/AccountInsertDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dto/AccountModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/entity/Account.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/api/MemberController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/application/MemberService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/dao/MemberDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/dao/mapper/MemberMapper.java
  backend/smart-logistics/src/main/resources/mapper/account/AccountMapper.xml
  backend/smart-logistics/src/main/resources/mapper/member/MemberMapper.xml
Labels: feat

#65 Refactor/common
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/item/api/ItemController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/item/application/ItemService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/interceptor/ExceptionAdviceHandler.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/aop/IpInsertAspect.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/exception/advice/GlobalControllerAdvice.java
  backend/smart-logistics/src/main/resources/logback-spring.xml
Labels: refactor

#67 hotfix: 물품 수정 로직 변경
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/item/api/ItemController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/item/application/ItemService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/item/dao/ItemDao.java
Labels: fix

#68 refactor: account 거래처코드 제거 #24
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/api/AccountController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/application/AccountService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dao/AccountDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dao/mapper/AccountMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dto/AccountInsertDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dto/AccountModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/entity/Account.java
  backend/smart-logistics/src/main/resources/mapper/account/AccountMapper.xml
Labels: refactor

#73 hotfix: SQL 쿼리 문제해결
  backend/smart-logistics/src/main/resources/mapper/item/ItemMapper.xml
Labels: refactor

#75 fix : 입고 코드 리팩토링 #74
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/dao/ReceiveDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/application/ReceiveItemService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/dto/ReceiveItemListDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/warehouse/dao/WarehouseDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/warehouse/dao/mapper/WarehouseMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/warehousestock/dao/WarehouseStockDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/warehousestock/dao/mapper/WarehouseStockMapper.java
  backend/smart-logistics/src/main/resources/mapper/receiveitem/ReceiveItemMapper.xml
  backend/smart-logistics/src/main/resources/mapper/warehouse/WarehouseMapper.xml
  backend/smart-logistics/src/main/resources/mapper/warehousestock/WarehouseStockMapper.xml
Labels: fix

#77 fix : 입고 관련 코드 보완 #76
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/api/ReceiveController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/application/ReceiveService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/dao/ReceiveDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/dao/mapper/ReceiveMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/dto/ReceiveListDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/api/ReceiveItemController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/dao/ReceiveItemDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/dao/mapper/ReceiveItemMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/dto/ReceiveItemListDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/dto/ReceiveItemModifyDto.java
  backend/smart-logistics/src/main/resources/mapper/receive/ReceiveMapper.xml
  backend/smart-logistics/src/main/resources/mapper/receiveitem/ReceiveItemMapper.xml
Labels: fix
