Repository 2Jo-Logistics-Management/smart-logistics-back, pull requests merged in 2023-08, with the labels that each got.

#26 Member/login
  backend/smart-logistics/pom.xml
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/api/AccountController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/application/AccountService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dao/AccountDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dao/mapper/AccountMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dto/AccountInsertDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/dto/AccountModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/entity/Account.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/entity/Member.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/api/MemberController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/application/MemberService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/dao/MemberDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/dao/mapper/MemberMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/dto/LoginDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/interceptor/Auth.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/interceptor/AuthException.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/interceptor/ExceptionAdviceHandler.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/interceptor/InterceptorConfig.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/interceptor/SessionAuthInterceptor.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/aop/IpInseartAspect.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/aop/IpModifyAspect.java
  backend/smart-logistics/src/main/resources/application.properties
  backend/smart-logistics/src/main/resources/mapper/account/AccountMapper.xml
  backend/smart-logistics/src/main/resources/mapper/member/MemberMapper.xml
Labels: feat

#27 Swagger/swagger managements
  backend/smart-logistics/pom.xml
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/item/api/ItemController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/item/dao/mapper/ItemMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/item/dto/ItemInsertDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/item/dto/ItemModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porder/api/POrderController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porder/dto/POrderInsertDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porder/dto/POrderModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porderitem/api/POrderItemController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porderitem/dto/POrderItemInsertDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porderitem/dto/POrderItemModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/config/SpringFoxConfig.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/response/CommonResponse.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/response/ErrorResponse.java
  backend/smart-logistics/src/main/resources/application.properties
  backend/smart-logistics/src/main/resources/mapper/item/ItemMapper.xml
Labels: common

#28 fix: pom.xml 누락 코드 수정
  backend/smart-logistics/pom.xml
Labels: fix

#38 Log/log managements
  backend/smart-logistics/pom.xml
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/interceptor/ExceptionAdviceHandler.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/exception/advice/GlobalControllerAdvice.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/response/CommonResponse.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/response/ErrorResponse.java
  backend/smart-logistics/src/main/resources/application-dev.properties
  backend/smart-logistics/src/main/resources/application-prod.properties
  backend/smart-logistics/src/main/resources/logback-spring.xml
Labels: common

#44 Receive/refactoring aop
  backend/smart-logistics/pom.xml
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/entity/CmpPOrder.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/entity/ReceiveList.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/api/ReceiveController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/application/ReceiveService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/dao/ReceiveDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/dao/mapper/ReceiveMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/dto/CmpPOrderDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/dto/ReceiveInsertDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/dto/ReceiveListDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/dto/ReceiveModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/api/ReceiveItemController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/dao/mapper/ReceiveItemMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/dto/ReceiveItemDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/dto/ReceiveItemInsertDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/dto/ReceiveItemModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/aop/advisor/TimeOutAspect.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/aop/advisor/TimeTraceAspect.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/aop/annotation/TimeOut.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/aop/annotation/TimeTrace.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/config/SpringFoxConfig.java
  backend/smart-logistics/src/main/resources/application-dev.properties
  backend/smart-logistics/src/main/resources/mapper/receive/ReceiveMapper.xml
Labels: feat

#46 Monitoring/monitoring managements
  backend/smart-logistics/pom.xml
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/interceptor/ExceptionAdviceHandler.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/config/SpringFoxConfig.java
  backend/smart-logistics/src/main/resources/application-dev.properties
  backend/smart-logistics/src/main/resources/application-dev.yml
Labels: feat, common

#50 Refactor/porder item managements
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/entity/POrder.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/entity/POrderItem.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/item/dao/mapper/ItemMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porder/dao/POrderDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porder/dao/mapper/POrderMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porder/dto/POrderModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porder/exception/InvalidStateException.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porder/exception/UnModifiableStateException.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porderitem/api/POrderItemController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porderitem/application/POrderItemService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porderitem/dao/POrderItemDao.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porderitem/dao/mapper/POrderItemMapper.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porderitem/dto/POrderItemInsertDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porderitem/dto/POrderItemModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/porderitem/dto/POrderItemStateModifyDto.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receive/api/ReceiveController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/receiveitem/api/ReceiveItemController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/aop/IpModifyAspect.java
  backend/smart-logistics/src/main/resources/mapper/item/ItemMapper.xml
  backend/smart-logistics/src/main/resources/mapper/porder/POrderMapper.xml
  backend/smart-logistics/src/main/resources/mapper/porderitem/POrderItemMapper.xml
Labels: feat, refactor

#53 Swagger/swagger member
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/api/AccountController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/account/application/AccountService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/api/MemberController.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/domain/member/application/MemberService.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/config/WebConfiguration.java
  backend/smart-logistics/src/main/java/com/douzon/smartlogistics/global/common/filter/CorsFilter.java
Labels: feat
